### ISSUE TITLE
InputRow text chopped off on Android with RN 0.28

### ISSUE THREAD

**Issue by jamieathans** [panza-org/panza#18]
Can verify this was woking with 0.27.2.

![screenshot_20160624-171142](https://cloud.githubusercontent.com/assets/16371427/16331736/5304247c-3a31-11e6-8419-cf4810225d54.png)

**Comment by bmcmahen** [comment]
Thanks. I'll look into RN 0.28 support this afternoon.

**Comment by bmcmahen** [comment]
This is fixed in v3.
