### ISSUE TITLE
Text "g" rendering on Android

### ISSUE THREAD

**Issue by ruskid** [panza-org/panza#39]
I am using v3 of panza. 
Text component doesn't render "g" as it should on android device.
And text in buttons is not centered vertically, now i have paddingBottom: 5 as a temp fix 

![screenshot_2016-09-05-13-15-47](https://cloud.githubusercontent.com/assets/8279841/18258107/cd0b1bcc-73cf-11e6-9035-f599cb239f08.jpeg)

**Comment by bmcmahen** [comment]
What does your button code specifically look like?

**Comment by ruskid** [comment]
```javascript
const { style } = this.props

    return (
      <PanzaButton
        primary {...this.props}
        style={[Style.fixButton].concat(style)}  />

export default {
  fixButton: {
    paddingBottom: (Platform.OS === 'ios') ? 0 : 5,
  }
}
```

I didn't test panza on ios, so it's 0.

**Comment by bmcmahen** [comment]
Yeah, this is really strange. iOS and android seem to have different line-height behaviour. I'm almost considering removing lineheight, since it doesn't seem very predictable. Trying to find the best solution for this...

**Comment by bmcmahen** [comment]
The primary issue is that iOS react-native renders line-height such that the text is positioned at the bottom of the line-height, and not in the middle (as it does on the web). The android line-height seems to render differently, and clips the text if the line-height isn't sufficient. The kinda crappy fix for this now is to just up the line-height on android.

**Comment by ruskid** [comment]
Will check it tomorrow and confirm! thanks!
